// packages/s2-react/src/components/sheets/base-sheet/index.tsx
import { getSafetyDataConfig, S2_PREFIX_CLS, SpreadSheet } from '@tant/s2';
import { Spin } from 'antd';
import React from 'react';
import { useSpreadSheet } from '../../../hooks/useSpreadSheet';
import { SpreadSheetContext } from '../../../utils/SpreadSheetContext';
import { getSheetComponentOptions } from '../../../utils';
import { Header } from '../../header';
import { S2Pagination } from '../../pagination';
import type {
  SheetComponentOptions,
  SheetComponentsProps,
} from '../../sheets/interface';

import './index.less';

export const BaseSheet = React.forwardRef<
  SpreadSheet,
  React.PropsWithChildren<SheetComponentsProps>
>((props, ref) => {
  const { dataCfg, options, header } = props;
  const { s2Ref, loading, containerRef, pagination, wrapperRef } =
    useSpreadSheet(props);

  const [contextVal, setContextVal] = React.useState<SpreadSheet>(
    s2Ref.current,
  );

  // 同步实例
  React.useEffect(() => {
    if (ref) {
      (ref as React.MutableRefObject<SpreadSheet>).current = s2Ref.current;
    }
  }, [ref, s2Ref]);

  React.useEffect(() => setContextVal(s2Ref.current), [setContextVal, s2Ref]);

  return (
    <React.StrictMode>
      <SpreadSheetContext.Provider value={contextVal}>
        <Spin spinning={loading} wrapperClassName={`${S2_PREFIX_CLS}-spin`}>
          <div ref={wrapperRef} className={`${S2_PREFIX_CLS}-wrapper`}>
            {header && (
              <Header
                {...header}
                sheet={s2Ref.current}
                style={{
                  width: options.width,
                }}
                dataCfg={getSafetyDataConfig(dataCfg)}
                options={getSheetComponentOptions(options)}
              />
            )}
            <div ref={containerRef} className={`${S2_PREFIX_CLS}-container`} />
            {pagination.showPagination && (
              <S2Pagination
                pagination={pagination.pagination}
                onChange={pagination.onChange}
                onShowSizeChange={pagination.onShowSizeChange}
              />
            )}
            {props.children}
          </div>
        </Spin>
      </SpreadSheetContext.Provider>
    </React.StrictMode>
  );
});

BaseSheet.displayName = 'BaseSheet';
BaseSheet.defaultProps = {
  options: {} as SheetComponentOptions,
  adaptive: false,
  showPagination: false,
};

// packages/s2-vue/src/components/sheets/base-sheet.vue
<script lang="ts">
import { S2_PREFIX_CLS } from '@tant/s2';
import { Spin } from 'ant-design-vue';
import { defineComponent } from 'vue';
import { isBoolean } from 'lodash';
import S2Pagination from '../pagination/index.vue';
import { useSpreadSheet } from '../../hooks/useSpreadSheet';
import {
  initBaseSheetEmits,
  initBaseSheetProps,
} from '../../utils/initPropAndEmits';

export default defineComponent({
  name: 'BaseSheet',
  props: initBaseSheetProps(),
  emits: initBaseSheetEmits(),
  setup(props, ctx) {
    const { wrapperRef, containerRef, s2Ref, loading, pagination } =
      useSpreadSheet(props, ctx.emit);

    ctx.expose({
      get instance() {
        return s2Ref.value;
      },
    });

    const handlePageChange = (nextCurrent: number) => {
      if (props.showPagination && !isBoolean(props.showPagination)) {
        props.showPagination.onChange?.(nextCurrent);
      }
      pagination.change(nextCurrent);
    };

    const handlePageSizeChange = (nextSize: number) => {
      if (props.showPagination && !isBoolean(props.showPagination)) {
        props.showPagination.onShowSizeChange?.(nextSize);
      }
      pagination.showSizeChange(nextSize);
    };

    return {
      S2_PREFIX_CLS,
      wrapperRef,
      containerRef,
      s2Ref,
      loading,
      pagination,
      handlePageChange,
      handlePageSizeChange,
    };
  },
  components: {
    Spin,
    S2Pagination,
  },
});
</script>

<template>
  <Spin :wrapperClassName="S2_PREFIX_CLS + '-spin'" :spinning="loading">
    <div ref="wrapperRef" :class="S2_PREFIX_CLS + '-wrapper'">
      <div ref="containerRef" :class="S2_PREFIX_CLS + '-container'" />
      <S2Pagination
        v-if="pagination.visible.value"
        :current="pagination.current.value"
        :pageSize="pagination.pageSize.value"
        :total="pagination.total.value"
        @change="handlePageChange"
        @showSizeChange="handlePageSizeChange"
      />
    </div>
  </Spin>
</template>

<style lang="less">
@import '../../styles/variable.less';

.@{preCls} {
  &-spin.ant-spin-nested-loading,
  &-spin > .ant-spin-container {
    height: 100%;
  }

  &-wrapper {
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  &-container {
    overflow: auto;
    flex: 1 1 auto;

    canvas {
      display: block;
    }
  }

  &-pagination {
    display: flex;
    align-items: center;
    z-index: 1024;

    &-count {
      margin-left: 12px;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: 64px;
    }
  }
}
</style>
