// packages/s2-vue/src/components/tooltip/components/summary.vue
<script lang="ts">
import { size, reduce } from 'lodash';
import {
  i18n,
  type TooltipSummaryProps,
  type TooltipSummaryOptions,
  TOOLTIP_PREFIX_CLS,
} from '@tant/s2';
import { computed, defineComponent } from 'vue';
import type { GetInitProps } from '../../../interface';

export default defineComponent({
  name: 'TooltipSummary',
  props: ['summaries'] as unknown as GetInitProps<TooltipSummaryProps>,
  setup(props) {
    const summaryInfo = computed(() =>
      reduce(
        props.summaries,
        (pre, next) => {
          pre.count += size(next?.selectedData);
          if (next.value || next.name) {
            pre.summaries.push(next);
          }
          return pre;
        },
        { count: 0, summaries: [] } as {
          count: number;
          summaries: Array<TooltipSummaryOptions>;
        },
      ),
    );

    return {
      summaryInfo,
      i18n,
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {},
});
</script>

<template>
  <div :class="`${TOOLTIP_PREFIX_CLS}-summary`">
    <div :class="`${TOOLTIP_PREFIX_CLS}-summary-item`">
      <span :class="`${TOOLTIP_PREFIX_CLS}-selected`">
        {{ summaryInfo.count }} {{ i18n('项') }}
      </span>
      {{ i18n('已选择') }}
    </div>
    <div
      v-for="summary in summaryInfo.summaries"
      :key="`${summary.name}-${summary.value}`"
      :class="`${TOOLTIP_PREFIX_CLS}-summary-item`"
    >
      <span :class="`${TOOLTIP_PREFIX_CLS}-summary-key`">
        {{ summary.name }} {{ i18n('总和') }}
      </span>
      <span
        :class="`${TOOLTIP_PREFIX_CLS}-summary-val ${TOOLTIP_PREFIX_CLS}-bold`"
      >
        {{ summary.value }}
      </span>
    </div>
  </div>
</template>

<style lang="less"></style>

// packages/s2-react/src/components/tooltip/components/summary.tsx
import React from 'react';
import { size, sumBy } from 'lodash';
import { i18n, TOOLTIP_PREFIX_CLS, type TooltipSummaryProps } from '@tant/s2';
import cls from 'classnames';

export const TooltipSummary: React.FC<TooltipSummaryProps> = React.memo(
  (props) => {
    const { summaries = [] } = props;

    const renderSelected = () => {
      const count = sumBy(summaries, (item) => size(item?.selectedData));
      return (
        <div className={`${TOOLTIP_PREFIX_CLS}-summary-item`}>
          <span className={`${TOOLTIP_PREFIX_CLS}-selected`}>
            {count} {i18n('项')}
          </span>
          {i18n('已选择')}
        </div>
      );
    };

    const renderSummary = () => {
      return summaries?.map((item) => {
        const { name = '', value } = item || {};
        if (!name && !value) {
          return;
        }

        return (
          <div
            key={`${name}-${value}`}
            className={`${TOOLTIP_PREFIX_CLS}-summary-item`}
          >
            <span className={`${TOOLTIP_PREFIX_CLS}-summary-key`}>
              {name}（{i18n('总和')})
            </span>
            <span
              className={cls(
                `${TOOLTIP_PREFIX_CLS}-summary-val`,
                `${TOOLTIP_PREFIX_CLS}-bold`,
              )}
            >
              {value}
            </span>
          </div>
        );
      });
    };

    return (
      <div className={`${TOOLTIP_PREFIX_CLS}-summary`}>
        {renderSelected()}
        {renderSummary()}
      </div>
    );
  },
);
