// packages/s2-react/src/components/tooltip/components/head-info.tsx
import React from 'react';
import {
  type TooltipDetailListItem,
  type TooltipHeadInfo,
  TOOLTIP_PREFIX_CLS,
} from '@tant/s2';

export const TooltipHead: React.FC<TooltipHeadInfo> = (props) => {
  const { rows = [], cols = [] } = props;

  return (
    <div className={`${TOOLTIP_PREFIX_CLS}-head-info-list`}>
      {cols.map((item: TooltipDetailListItem) => item.value)?.join('/')}
      {cols.length > 0 && rows.length > 0 && '，'}
      {rows.map((item: TooltipDetailListItem) => item.value)?.join('/')}
    </div>
  );
};

// packages/s2-vue/src/components/tooltip/components/head-info.vue
<script lang="ts">
import { type TooltipHeadInfo, TOOLTIP_PREFIX_CLS } from '@tant/s2';
import { defineComponent, type PropType } from 'vue';
import type { GetInitProps } from '../../../interface';

export default defineComponent({
  name: 'TooltipHeadInfo',
  props: ['rows', 'cols'] as unknown as GetInitProps<TooltipHeadInfo>,
  setup() {
    return {
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {},
});
</script>

<template>
  <div
    v-if="cols?.length || rows?.length"
    :class="`${TOOLTIP_PREFIX_CLS}-head-info-list`"
  >
    <span v-for="col in cols" :key="col.value">{{ col.value }}/</span>
    <span v-if="cols?.length > 0 && rows?.length > 0">，</span>
    <span v-for="row in rows" :key="row.value">{{ row.value }}/</span>
  </div>
</template>

<style lang="less"></style>
