// packages/s2-react/src/components/tooltip/components/infos.tsx
import React from 'react';
import { TOOLTIP_PREFIX_CLS } from '@tant/s2';
import type { TooltipInfosProps } from '../interface';

export const TooltipInfos: React.FC<TooltipInfosProps> = (props) => {
  const { infos = '' } = props;

  return <div className={`${TOOLTIP_PREFIX_CLS}-infos`}>{infos}</div>;
};

// packages/s2-vue/src/components/tooltip/components/infos.vue
<script lang="ts">
import { TOOLTIP_PREFIX_CLS } from '@tant/s2';
import { defineComponent } from 'vue';
import type { GetInitProps } from '../../../interface';
import type { TooltipInfosProps } from '../interface';

export default defineComponent({
  name: 'TooltipInfos',
  props: ['infos'] as unknown as GetInitProps<TooltipInfosProps>,
  setup() {
    return {
      TOOLTIP_PREFIX_CLS,
    };
  },
  components: {},
});
</script>

<template>
  <div :class="`${TOOLTIP_PREFIX_CLS}-infos`">{{ infos }}</div>
</template>

<style lang="less"></style>
